apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
  labels:
    app: {{ .Chart.Name }}
    component: backend
data:
{{- range $key, $value := .Values.configMaps.backendConfig }}
  {{ $key }}: "{{ $value }}"
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-config
  labels:
    app: {{ .Chart.Name }}
    component: frontend
data:
{{- range $key, $value := .Values.configMaps.frontendConfig }}
  {{ $key }}: "{{ $value }}"
{{- end }}
