apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
  labels:
    app: {{ .Chart.Name }}
    component: backend
data:
{{- range $key, $value := .Values.configMaps.backend-config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-config
  labels:
    app: {{ .Chart.Name }}
    component: frontend
data:
{{- range $key, $value := .Values.configMaps.frontend-config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
