apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.backend.service.name }}
  labels:
    app: {{ .Chart.Name }}
    component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
  selector:
    app: {{ .Chart.Name }}
    component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.frontend.service.name }}
  labels:
    app: {{ .Chart.Name }}
    component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      nodePort: {{ .Values.frontend.service.nodePort }}
  selector:
    app: {{ .Chart.Name }}
    component: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.redis.service.name }}
  labels:
    app: {{ .Chart.Name }}
    component: redis
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
  selector:
    app: {{ .Chart.Name }}
    component: redis
