replicaCount: 1

# Backend configuration
backend:
  image:
    repository: shreybatra/sample-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    name: backend-svc
    port: 8000
  configMapName: backend-config

# Frontend configuration
frontend:
  image:
    repository: shreybatra/sample-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    name: frontend-svc
    port: 5175
    nodePort: 31000
  configMapName: frontend-config

# Redis configuration
redis:
  image:
    repository: redis
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    name: redis-svc
    port: 6379

# ConfigMap data
configMaps:
  backendConfig:
    REDIS_URI: redis://redis-svc:6379
  frontendConfig:
    BACKEND_URL: http://backend-svc:8000

# Service Account configuration
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Pod configuration
podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

# Service configuration
service:
  type: ClusterIP
  port: 80

# Ingress is not used in this task
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

# Resources - leave empty to adapt to different environments
resources: {}

# Probes
livenessProbe:
  httpGet:
    path: /
    port: 8000
readinessProbe:
  httpGet:
    path: /
    port: 8000

# Autoscaling (not required for this task but configurable for future)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

# Node affinity, tolerations, and selectors (not required in this task)
nodeSelector: {}
tolerations: []
affinity: {}

namespace: default
